### ISSUE TITLE
[Win10 GTAIV Borderless Windowed]

### ISSUE THREAD

**Issue by Kevin-from-HP** [elishacloud/dxwrapper#125] opened 2021-05-03 13:11 UTC
Fresh GTAIV Complete Edition install, following Catsmakaroo's Ultimate GTAIV Install procedures, and he does not seem to have this issue but borderless windowed does not work as in:

- Game opens in Brdless Window without dxwrapper;
- With dxwrapper game opens in Bordered Window, have to change settings in game for borderless to apply;
- Configuring through .ini changes nothing.

Using .asi and .ini files only.

**Comment by elishacloud** [comment] 2021-05-03 21:17
Can you upload the log file and the ini file you are using?

**Comment by Kevin-from-HP** [comment] 2021-05-03 22:38
Managed to circumvent the issue:
Somehow, setting fullscreen to 1 in .ini makes the game launch in borderless windowed mode.

Uploading both logs, one launch with fullscreen=0, changing settings in-game causing it to go borderless, and one launch with fullscreen=1, with game launching in borderless.

Extra info:
Using it alongside DXVK, and with FusionFix and Zolika patches, which do some Borderless patching, but again, Catsmakaroo didn't seem to have this issue with the same setup. Weird.

[(fullscreen 0) dxwrapper-playgtaiv.log](https://github.com/elishacloud/dxwrapper/files/6418190/fullscreen.0.dxwrapper-playgtaiv.log)
[(fullscreen 1) dxwrapper-playgtaiv.log](https://github.com/elishacloud/dxwrapper/files/6418191/fullscreen.1.dxwrapper-playgtaiv.log)

**Comment by elishacloud** [comment] 2021-05-04 01:37
Try using this updated dxwrapper build.  Make sure to update the ini file as needed.

[dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/6418667/dxwrapper.zip)

**Comment by Kevin-from-HP** [comment] 2021-05-04 03:21
Ty for taking a look at it.
Game doesn't boot, as in, initial blackscreen and then stops responding.
Log below:

[dxwrapper-playgtaiv.log](https://github.com/elishacloud/dxwrapper/files/6418852/dxwrapper-playgtaiv.log)

**Comment by elishacloud** [comment] 2021-05-04 20:36
Can you send me your ini file?  What options do you have enabled?  What are you trying to do?

It looks like the issue is with `DDrawCompat`.  You may want to try disabling that.

**Comment by Kevin-from-HP** [comment] 2021-05-04 23:45
My .ini is as follows:

Everything as it comes from download, except DDrawCompat = 1 and DDrawCompatNoProcAffinity  = 1.
As I said, issue is circumvented with Fullscreen toggled, it launches in Borderless, assuming it is still working (is it working then?)

With DDrawCompat, NoProcAffinity and Fullscreen OFF, game launches in Borderless as it should :)
Log: [dxwrapper-playgtaiv.log](https://github.com/elishacloud/dxwrapper/files/6424438/dxwrapper-playgtaiv.log)

What does DDrawCompat do? Is this setting better than DDrawCompat and Fullscreen ON for GTAIV alongside DXVK? I've no idea how this works internally so idk

**Comment by elishacloud** [comment] 2021-05-05 04:53
> What does DDrawCompat do?

DDrawCompat is just a DirectDraw compatibility layer between the game and Windows to a improve to allow older game to function correctly on newer operating systems.

I don't know much about GTAIV, but if `Fullscreen =1` does what you want then good.  But from the latest log it appears that the dxwrapper is not doing anything.  From searching the Internet it looks like GTAIV uses DirectX9. If that is the case than enabling DDrawCompat would do you no good since DDrawCompat only works on DirectX up to version 7.

It also appears that dxwrapper is not able to hook DirectX9 APIs.  I added a fix for this and pre-configured the ini file for you.

Try this update: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/6425105/dxwrapper.zip)

**Comment by Kevin-from-HP** [comment] 2021-05-05 11:26
With this one game doesn't actually boot, not even a blackscreen. I'm starting to feel bad about this haha

Logs: 
[NEW UPDATED Fullscr = 1 dxwrapper-playgtaiv.log](https://github.com/elishacloud/dxwrapper/files/6426683/NEW.UPDATED.Fullscr.1.dxwrapper-playgtaiv.log)
[NEW UPDATED FScr = 0 dxwrapper-playgtaiv.log](https://github.com/elishacloud/dxwrapper/files/6426684/NEW.UPDATED.FScr.0.dxwrapper-playgtaiv.log)

And for any sort of reference, a boot with the Github release, with EVERYTHING set to 0 (or as it comes):
[dxwrapper-playgtaiv.log](https://github.com/elishacloud/dxwrapper/files/6426700/dxwrapper-playgtaiv.log)
This one launching in Borderless, (assuming Wrapper is working?)

Might be dumb, but dxwrapper .dll must be used alongside the .asi?

**Comment by elishacloud** [comment] 2021-05-06 07:20
> With this one game doesn't actually boot, not even a blackscreen. I'm starting to feel bad about this haha

Yeah, I made a mistake with the hooking.  Let me work on a fix for that.

> This one launching in Borderless, (assuming Wrapper is working?)

It is not really doing much in this mode.  But if this is all you need than that is fine.

> Might be dumb, but dxwrapper .dll must be used alongside the .asi?

No.  You only need either the .dll or the .asi, not both.

**Comment by elishacloud** [comment] 2021-05-08 20:05
Ok, I think I fixed the hooking issue.  Please try with the testing build below.

Updated testing build: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/6446482/dxwrapper.zip)

**Comment by Kevin-from-HP** [comment] 2021-05-10 20:33
Ok, I've only changed fullscreen to 0 from the .ini. I'm going to assume it's working, but it breaks some stuff ingame, as the map menu is missing textures and theres a weird square around the minimap.

![2](https://user-images.githubusercontent.com/83590578/117720988-01766f00-b1e8-11eb-972a-f18b4172e5a0.PNG)

![1](https://user-images.githubusercontent.com/83590578/117720966-fae7f780-b1e7-11eb-8575-b34f79fa872d.PNG)

Log: 
[dxwrapper-playgtaiv.log](https://github.com/elishacloud/dxwrapper/files/6454825/dxwrapper-playgtaiv.log)

**Comment by elishacloud** [comment] 2021-05-10 21:52
Perfect.  Thanks for helping troubleshoot this.

**Comment by AgentHitman47** [comment] 2024-01-31 15:50
Bro where is that "Fullscreen" in .ini file? There's "BorderlessWindowed" and "BlackscreenFix" but I couldn't find that "Fullscreen" which I can change to 0.
![IMG_20240131_214348](https://github.com/elishacloud/dxwrapper/assets/158301420/8eaf89ca-6252-4973-9705-09af74463d87)

![IMG_20240131_214625](https://github.com/elishacloud/dxwrapper/assets/158301420/5043524d-64ee-4854-9b74-f8b1ba8179da)
![IMG_20240131_214614](https://github.com/elishacloud/dxwrapper/assets/158301420/a362c50a-f0d4-4704-8cf5-183254ed430f)
![IMG_20240131_214606](https://github.com/elishacloud/dxwrapper/assets/158301420/642c7f9d-a2b1-40f1-85c4-043dd8379255)
![IMG_20240131_214552](https://github.com/elishacloud/dxwrapper/assets/158301420/094c0c9a-a292-4e49-86e3-5abc5f946582)
![IMG_20240131_214540](https://github.com/elishacloud/dxwrapper/assets/158301420/e745c3a8-21ff-4717-9500-8741f51c3d9a)
![IMG_20240131_214528](https://github.com/elishacloud/dxwrapper/assets/158301420/175ee1e3-e2c3-493e-ba75-833799c13c6b)
![IMG_20240131_214510](https://github.com/elishacloud/dxwrapper/assets/158301420/d26bf0cf-f81f-47a0-b111-c818aa061b1c)
![IMG_20240131_214458](https://github.com/elishacloud/dxwrapper/assets/158301420/7ae86396-986f-4c4a-8f3e-2db29a4ea91c)
![IMG_20240131_214440](https://github.com/elishacloud/dxwrapper/assets/158301420/c33c5dbc-02e4-4f6a-8211-e2b4273c5b27)
![IMG_20240131_214408](https://github.com/elishacloud/dxwrapper/assets/158301420/32b6d79c-a739-482d-a9b8-d05681fd6cf4)
 to 0. 
![IMG_20240131_214707](https://github.com/elishacloud/dxwrapper/assets/158301420/7edd9452-480a-4560-8f61-a26f892fa79d)
![IMG_20240131_214657](https://github.com/elishacloud/dxwrapper/assets/158301420/839b501a-9c82-4a77-bb02-e2cf963147b3)
![IMG_20240131_214645](https://github.com/elishacloud/dxwrapper/assets/158301420/eb848eaf-c458-4540-9901-2d1f3278d0dc)
![IMG_20240131_214635](https://github.com/elishacloud/dxwrapper/assets/158301420/3ef15599-f48f-4351-b675-ed510ac24b37)

**Comment by elishacloud** [comment] 2024-01-31 19:55
The "Fullscreen" in .ini file is in the dxwrapper.ini file not in the ZolikaPatch.ini file.

**Comment by AgentHitman47** [comment] 2024-02-01 06:45
But the disclaimer doesn't even end. It remains still.
![Screenshot_2024-02-01-12-42-09-79_b6022cb7d1a61f21e4fe914c8728a54c](https://github.com/elishacloud/dxwrapper/assets/158301420/1d7b1746-4e2b-457e-8ad8-2894474c0f91)

**Comment by AgentHitman47** [comment] 2024-02-01 06:56
Well, the disclaimer issue got fixed but still facing the same black screen problem.
![Screenshot_2024-02-01-12-53-09-29_b6022cb7d1a61f21e4fe914c8728a54c](https://github.com/elishacloud/dxwrapper/assets/158301420/c2dba8fa-79d6-44b7-8957-dd51d3e809b2)

**Comment by elishacloud** [comment] 2024-02-02 01:05
Can you upload the dxwrapper log file and ini file?

**Comment by AgentHitman47** [comment] 2024-02-02 08:35
[dxwrapper-playgtaiv.log](https://github.com/elishacloud/dxwrapper/files/14137382/dxwrapper-playgtaiv.log)
[dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/14137383/dxwrapper.zip)
I downloaded the zip file which you gave and the log file which Kevin-from-HP gave.

**Comment by AgentHitman47** [comment] 2024-02-02 08:43
Btw GTA 4 only runs when I download Zolika patch. Otherwise the game doesn't open. The Black screen issue is because of Zolika patch. Which version of Zolika patch did you download and how did you manage to get the game run without black screen?
![Screenshot_2024-02-02-14-38-24-29_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/elishacloud/dxwrapper/assets/158301420/68420606-9c2a-4b92-bff6-49fb724dd3bd)
![Screenshot_2024-02-02-14-38-32-44_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/elishacloud/dxwrapper/assets/158301420/1c05c1ff-c992-4f4b-88c9-dc4aa2e7f11a)
![Screenshot_2024-02-02-14-38-39-75_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/elishacloud/dxwrapper/assets/158301420/f48e2080-4f2d-4e69-a47e-39c0ac55712e)
![Screenshot_2024-02-02-14-38-50-04_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/elishacloud/dxwrapper/assets/158301420/2d9b1683-5ab0-4363-90ae-53331744fdbb)
![Screenshot_2024-02-02-14-38-57-41_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/elishacloud/dxwrapper/assets/158301420/843a54b8-02c8-4579-a298-e777ca5bcd3b)

**Comment by AgentHitman47** [comment] 2024-02-02 08:45
Btw I downloaded only GTA 4 Niko Bellic edition or main edition whatever you call it, not the complete edition.

**Closed** 2024-12-11 01:44 UTC
