### ISSUE TITLE
Tropico Mouse Scaling Native Resolution Issue

### ISSUE THREAD

**Issue by nickkeane** [elishacloud/dxwrapper#243] opened 2023-12-08 00:12 UTC
I have Tropico set up to use Dd7to9 with the following:

Dd7to9=1
DdrawFixByteAlignment=1
DdrawUseNativeResolution=1
DdrawIntegerScalingClamp=1
DdrawMaintainAspectRatio=1

And it creates a window fine, but when I move the mouse around, the menu is interacting as if there's a small area in the top left corner (like 0,0 to 640,480px or 800,600px) of the screen that's the active mouse area where I'll move the mouse around and it will select menu items. Actually moving my mouse over the menu items does not select them. So it looks like the screen-space range for my mouse is not scaling up to my computer's full native resolution (2560x1440px) + 4:3 aspect ratio + Intscaling with those settings.

<img width="1280" alt="image" src="https://github.com/elishacloud/dxwrapper/assets/770042/1a53e138-597d-4a04-9b83-a7b382033338">

Blue Circle is where mouse cursor is when "Exit" is selected.

**Comment by elishacloud** [comment] 2023-12-08 01:07
I believe this is the same issue reported in #176.  The fix for this is to hook the mouse cursor and adjust it to scale to the new screen resolution.  I am not really planning to fix this anytime soon.  dxwrapper has only best effort support for scaling.  Best to run this game in the game's supported resolution.

**Comment by elishacloud** [comment] 2024-05-12 23:58
Closing this as duplicate of #176

**Closed by elishacloud** 2024-05-12 23:58 UTC
