### ISSUE TITLE
How to make RealDllPath work? Using dxwrapper with Colin McRae Rally 1

### ISSUE THREAD

**Issue by daninthemix** [elishacloud/dxwrapper#131] opened 2021-07-04 08:23 UTC
I'm trying to use DxWrapper with Colin McRae Rally 1, and also DgVoodoo.

DxWrapper because it's the only way to have the game actually run smoothly. And DgVoodoo to run it in high resolution and without changing my desktop res to 800x600 (grrrr!).

The only 2 lines I edited in dxwrapper.ini are:

Dd7to9                     = 1
RealDllPath                = C:\Games\Misc\CMRally\D3D9.dll

The latter is a DgVoodoo dll. But I only got DxWrapper, not DgVoodoo.

What am I doing wrong here?

**Comment by daninthemix** [comment] 2021-07-04 08:27
Oops, my ini needed to match the dll file name. It now adds DgVoodoo to the mix, but then crashes.

**Comment by daninthemix** [comment] 2021-07-04 08:36
Well, the FullscreenWindowMode and DxWnd options outright crash. Is it literally impossible to run this damn game without changing my desktop res?

**Comment by elishacloud** [comment] 2021-07-05 08:10
> Dd7to9 = 1

This game uses Direct3D and the `Dd7to9` option does not yet work with Direct3D games.

> It now adds DgVoodoo to the mix, but then crashes.

If you are using the `Dd7to9` option that could be why it is crashing.

> Well, the FullscreenWindowMode and DxWnd options outright crash.

For this game, the `FullscreenWindowMode` option requires the `Dd7to9` option which does not work with this game.

I added a quick hack for this game that will stretch the image to fill the screen without changing resolutions.  Try using this wrapper update:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/6762718/dxwrapper.zip)

**Comment by elishacloud** [comment] 2024-12-10 21:58
Closing this as a duplicate of #32.  I do have progress on this game and it is playable with the latest dev build,

**Closed by elishacloud** 2024-12-10 21:58 UTC
