### ISSUE TITLE
[Star Trek Armada] Doesn't start

### ISSUE THREAD

**Issue by Cerxi** [elishacloud/dxwrapper#17] opened 2018-03-03 14:10 UTC
Windows 10, Nvidia GTX 960

I've installed a fresh copy of Armada, to remove every trace of old tools, but your fix doesn't seem to work. It crashes on startup, before even the menu. On the Fleetops forum, you ask for a ddraw-armada.log, but it's not generating one of those at all. The closest thing is draw-splash.log, which generates from running Splash.exe and clicking "play", which I've attached. Running Armada.exe simply shows the orange Armada box for a moment, and then crashes.

[ddraw-splash.log](https://github.com/elishacloud/dxwrapper/files/1777520/ddraw-splash.log)

**Comment by elishacloud** [comment] 2018-03-04 00:19
@Cerxi, If you are not seeing a ddraw-armada.log file then it means that the wrapper is not getting loaded.  Try renaming the two files to dsound.dll and dsound.ini, respectively.

**Comment by Cerxi** [comment] 2018-03-04 21:45
The game still crashes, but now it crashes about twice as fast, and it does generate a log file
[dsound-armada.log](https://github.com/elishacloud/dxwrapper/files/1778986/dsound-armada.log)

**Comment by thunderchero** [comment] 2018-03-05 18:06
I tested yesterday also and found an old compatibility setting set in windows registry 
open the regedit.exe and go to
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers
and delete any armada compatibility setting

**Comment by Cerxi** [comment] 2018-03-06 06:32
I've done as thunderchero suggested, and gone through the registry for any other lingering Armada compatibility settings, but even after paring those out, no change.

**Comment by elishacloud** [comment] 2018-03-08 06:59
From your log file it looks like your configuration file is wrong.  I see an error message:

```text
204796 13:45:02.114 Cannot load custom library: E:\Games\Star Trek - Armada
```

Can you send me your ini file?

**Comment by Cerxi** [comment] 2018-03-08 07:45
I haven't changed it from the download, but here
[ddraw.zip](https://github.com/elishacloud/dxwrapper/files/1792211/ddraw.zip)

**Comment by elishacloud** [comment] 2018-03-08 15:34
Can you send me your dsound.ini file?  This is the file that seems to have some wrong settings.  Also are you using both ddraw.dll and dsound.dll?  You can only use one or the other.  If you are using dsound.dll you need to delete ddraw.dll, and vice versa.

You need to either have this:
* ddraw.dll
* ddraw.ini

Or this:

* dsound.dll
* dsound.ini

I did find an issue with the old version of the files.  Try with this new one if you still have an issue:
[dsound.zip](https://github.com/elishacloud/dxwrapper/files/1793698/dsound.zip)

**Comment by Cerxi** [comment] 2018-03-10 02:35
That was the dsound.ini file, I renamed them back to ddraw at some point, sorry. I never had both at once.

I've tried with the new version, but it still crashes:
[dsound-armada.log](https://github.com/elishacloud/dxwrapper/files/1799003/dsound-armada.log)

**Comment by elishacloud** [comment] 2018-03-17 21:51
Hello Cerxi,

I am still unable to reproduce this, but there are a few more things you can try:

1. Delete "ARMADA.PRF" file from the _Start Trek Armada 1_ folder.

2. Try setting the following compatibility settings:
![compatibility](https://user-images.githubusercontent.com/25625456/37560224-c46061c4-29f1-11e8-92f9-6ed4fd74d25d.png)

3. Here is an updated patch.  This uses both ddraw.dll and dsound.dll.  Copy all **four** files from this zip into your _Start Trek Armada 1_ folder, overwriting any existing file.  [ddraw.zip](https://github.com/elishacloud/dxwrapper/files/1822113/ddraw.zip)

If this does not work please send me your "dxwrapper-armada.log" log file.

Note: you can also try opening the "dxwrapper.ini" file and setting `DDrawCompat` equal to `0` to disable it.  This will break the menu animations, but may allow you to get the game working.

**Comment by Cerxi** [comment] 2018-03-22 11:10
Sorry, took me a few days to get back to my email. Unfortunately, still doesn't work, even with compatibility settings, or with DDrawCompat set to 0. [dxwrapper-armada.log](https://github.com/elishacloud/dxwrapper/files/1837197/dxwrapper-armada.log)

**Comment by elishacloud** [comment] 2018-03-24 18:02
@Cerxi, I think this might be some setting with either Windows or with your graphics card.  Here are some things you might want to try:

1. Disable high DPI scaling in the Display Properties of your video card, by setting `Scale and layout` to 100%.  It is recommended to restart after this change.
2. Make sure you are using the latest Nvidia driver.
3. Disable vertical sync and G-Sync (if you have it) in your graphics card settings.
4. Check if you have an Nvidia profile setup for Armada and verify the settings are correct there.
5. Make sure you have installed _both_ Armada [patch 1.2](http://armadafiles.com/files/armada/official-releases/patches/star-trek-armada-12-patch/details) and Armada [patch 1.3](http://armadafiles.com/files/armada/mods/patches/star-trek-armada-patch-1-3-project/details).  Patch 1.2 needs to be installed first.
6. Try using [this](https://github.com/elishacloud/dxwrapper/files/1844655/ARMADA.zip) ARMADA.PRF file.

Let me know if any of these help you or not.

**Comment by Cerxi** [comment] 2018-03-24 18:44
So, embarrassingly, it turns out I didn't have 1.3 installed. After installing that, everything works (as long as I keep it in Win7 compatibility mode).

**Comment by thunderchero** [comment] 2018-03-24 18:46
I doubt if this will help but only way I can get Armada to load is to execute the armada.exe from install path. start menu short cuts crash every time.

**Comment by elishacloud** [comment] 2018-03-24 19:18
@Cerxi, great!  I am glad you got it working!

@thunderchero, sounds like you need to recreate the Start Menu item.

**Comment by elishacloud** [comment] 2018-03-24 19:30
@Cerxi, I updated the [wiki](https://github.com/elishacloud/dxwrapper/wiki/Start-Trek-Armada-1).  Would you mind testing with the lasted patch from the wiki to make sure it still works.

1. Delete ddraw.dll, dsound.dll, dxwrapper.dll and dxwrapper.ini from your Armada folder.
2. Download the updated patch files from the [wiki](https://github.com/elishacloud/dxwrapper/wiki/Start-Trek-Armada-1).

Please let me know if this works or not for you.  Thanks!

**Comment by Cerxi** [comment] 2018-03-25 02:35
Confirmed, it works. Actually, this one works even *without* compatibility settings on

**Comment by elishacloud** [comment] 2018-03-25 03:42
Ok, thanks for testing it!  I am closing the issue since it is now fixed.

**Closed by elishacloud** 2018-03-25 03:42 UTC
Labels: bug
