### ISSUE TITLE
Star Trek Armada: in game bik video not rendered correctly

### ISSUE THREAD

**Issue by yochenhsieh** [elishacloud/dxwrapper#246] opened 2023-12-27 15:40 UTC
OS: Windows 11
Armada-fix: 2023/10/03 (use Dd7to9)
dxwrapper.dll 1.1.6900.22

Can be observed in Federation mission 3, or any other mission that played bik video. 
![Armada 2023-12-27 23-31-08-83](https://github.com/elishacloud/dxwrapper/assets/1897377/6336264d-9030-4616-a73a-39fa6bde10d7)

Normal:
![Armada 2023-12-27 23-37-00-04](https://github.com/elishacloud/dxwrapper/assets/1897377/7a5c38e0-ed62-436b-b810-487ab1515da8)
The normal screenshot was using 2023/04 fix (use DDrawCompat)
dxwrapper.dll 1.0.6615.21

**Comment by elishacloud** [comment] 2023-12-28 20:26
That is the same thing that happens in #241 and #94.  It is a known issue with a number of Direct3D games when using dd7to9.  You could try disabling high DPI and seeing if that helps.  It has helped in some cases.

**Comment by yochenhsieh** [comment] 2023-12-28 23:14
High DPI was already disabled here. (Never enabled it before)
Any other option in dxwrapper that could help this?

**Comment by elishacloud** [comment] 2023-12-29 20:03
I don't think there are any settings in dxwrapper that can fix this right now.  It seems like the issue is that the game keeps writing to the same surface on top of itself causing it to be washed out.  I believe I need to clear the surface before letting the game write to the surface again.  I am just not quite sure what is the trigger to know when to clear the surface.  I plan to look into this later.

**Comment by elishacloud** [comment] 2024-03-17 01:43
This issue should be fixed in the latest build.  You can download it here:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/14625833/dxwrapper.zip)

**Comment by yochenhsieh** [comment] 2024-03-19 11:59
Confirmed this is fixed in above build. Thank you!!

**Closed** 2024-03-19 14:57 UTC
