### ISSUE TITLE
Army Men RTS bright issue with Dd7to9

### ISSUE THREAD

**Issue by SAM1430B** [elishacloud/dxwrapper#265] opened 2024-04-02 11:12 UTC
Hi,

The game looks like brighter than it should be.

Not sure if there are better settings or i'm messing something and i've tried all the options and it seems the problem still there.

I have copied ddraw.dll and dxwrapper.dll & .ini .

Thank you for your efforts and this awesome project.

![ArmyMenRTS](https://github.com/elishacloud/dxwrapper/assets/107554606/336b545b-fb8f-4189-862e-f779f4d4cb3a)
![ArmyMenRTS2](https://github.com/elishacloud/dxwrapper/assets/107554606/8b8a35fb-a2a4-44e8-9db3-b29cfcb93f3c)

**Comment by elishacloud** [comment] 2024-04-02 17:16
Can you upload the dxwrapper log file?

**Comment by SAM1430B** [comment] 2024-04-03 03:14
Sure thing.
[dxwrapper-amrts.log.txt](https://github.com/elishacloud/dxwrapper/files/14846225/dxwrapper-amrts.log.txt)

**Comment by elishacloud** [comment] 2024-04-03 17:15
Try with this update and let me know if you see any difference:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/14855988/dxwrapper.zip)

**Comment by SAM1430B** [comment] 2024-04-03 21:04
Yeah thank you, i've got better result.

i'm gonna test Dd7to9 combined with DDrawCompat next week and post a report.

Have a good night✨

**Comment by elishacloud** [comment] 2024-04-03 21:45
Ok, very good.  I am glad it is working better.

BTW:  DDrawCompat cannot be combined with Dd7to9.

**Comment by SAM1430B** [comment] 2024-04-17 21:45
I said next week but time flies so fast lol. Anyway after long play test it was flawless getting 60fps which is the most part i like. Except the smoke/dust look more dense.
![Army_Men_RTS_Screenshot_2024 04 17_-_22 38 08 36](https://github.com/elishacloud/dxwrapper/assets/107554606/b901d282-4549-447e-9edf-02792ff0b2ff)


Also i wanted to set a windowed screen with 1920x1080 size (which the game doesn't support it) tried `DdrawOverrideWidth`/`Height` seems making black frame rather than a stretched window, even `DdrawCustomWidth`/`Height` and `DdrawClippedWidth`/`Height` they seem not effecting anything.

**Comment by SAM1430B** [comment] 2024-04-19 19:57
Cool, we wish the best and everything goes smoothly.

**Comment by elishacloud** [comment] 2024-05-13 00:05
> > Except the smoke/dust look more dense.
> 
> This could be because I have not added MipMap support.

I added MipMap support.  See if this fixes the smoke/dust issue:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/15288013/dxwrapper.zip)

**Comment by SAM1430B** [comment] 2024-05-13 15:14
Seemed to be darker and smoke/dust issue still there.
![Screenshot_2024-05-13](https://github.com/elishacloud/dxwrapper/assets/107554606/f55b9832-c66a-42a4-9134-ab2250c907c3)

**Comment by elishacloud** [comment] 2024-05-13 15:26
That dark issue is a MipMap issue.  I guess it is an autogen issue.  I need to collect some logs.  Can you use the below build and send me the logs?

[dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/15296720/dxwrapper.zip)

**Comment by SAM1430B** [comment] 2024-05-13 18:20
Sure as you wish.
[dxwrapper-amrts.log.txt](https://github.com/elishacloud/dxwrapper/files/15298591/dxwrapper-amrts.log.txt)

**Comment by SAM1430B** [comment] 2024-05-14 10:24
You're right it wasn't long play.
I wish this would be what you want.
[dxwrapper-amrts.log.txt](https://github.com/elishacloud/dxwrapper/files/15306987/dxwrapper-amrts.log.txt)

**Comment by elishacloud** [comment] 2024-05-14 15:38
Ok, I think this one should fix the dark issue:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/15310761/dxwrapper.zip)

**Comment by elishacloud** [comment] 2024-05-16 05:06
This should fix everything in this game except the resizing.  There is another issue on that already.

**Comment by SAM1430B** [comment] 2024-05-16 09:58
Yes, except these two issues which one of them you're already going to add it (Resizing) in the future ✨.

**Comment by elishacloud** [comment] 2024-06-10 03:05
I can see the same (I believe it is the same) smoke issue with Dark Reign 2.  I have not looked into it yet, but I will check it out.

**Comment by SAM1430B** [comment] 2024-06-11 18:45
Yes, they made by the same engine.

**Comment by elishacloud** [comment] 2024-06-14 01:12
I know what the issue is but I don't know what is causing it or how best to fix it.  The issue is that the game calls `SetTextureStageState` and sets `D3DTSS_ALPHAOP` to `D3DTOP_SELECTARG1` when dd7to9 is enabled.  However, when using the native DirectDraw the game sets `D3DTSS_ALPHAOP` to `D3DTOP_MODULATE`.

If I overwrite the game and force the setting to `D3DTOP_MODULATE` when using dd7to9 it solves the issue.  However, that would break other games and is not a proper fix.  I am not quite sure why the game behaves differently here.

**Comment by SAM1430B** [comment] 2024-06-15 21:21
Yes, i've mentioned this before the game behaves different (e.g dd7to9 caps fps to 60, native to 30 fps) but this was in Windows 10 (not sure if this related).

Anyway i think the alternative way to fix it by making option to force `D3DTOP_MODULATE` (in the config file maybe).

**Comment by elishacloud** [comment] 2024-06-15 21:52
> Anyway i think the alternative way to fix it by making option to force `D3DTOP_MODULATE` (in the config file maybe).

Yes, I thought about that.  However, the issue is that there is a whole list of options that are available for `D3DTSS_ALPHAOP`.  In fact the game could send hundreds or thousands of requests to set that option per second.  How do I know which ones to force to `D3DTOP_MODULATE` and which ones should not?

I could just force `D3DTOP_SELECTARG1` to be `D3DTOP_MODULATE`.  That would probably work for this game and for Dark Reign 2.  But I am not sure how many other games this would work for,  Also, I prefer to fix this right the first time.  Once this is fixed correctly, the option won't be needed any more.  I hate to add an option and then remove it at some point when it is no longer needed.  But maybe I will do that for now.

**Comment by SAM1430B** [comment] 2024-06-15 22:51
I see your point and i think you don't have to be in a hurry at the moment, you might figure a way to find a better solution in the future to set it up. ✨

**Comment by elishacloud** [comment] 2024-09-08 00:07
This issue is caused by a failed call to `ValidateDevice()`.  I am looking for a solution.

**Comment by elishacloud** [comment] 2024-09-08 01:36
Ok, this update should fix the issue:  [dxwrapper.zip](https://github.com/user-attachments/files/16920345/dxwrapper.zip)

**Comment by SAM1430B** [comment] 2024-09-08 16:36
Nice thank you, works flawless 🩶


PS: there are additional steps to run the Army men RTS with DxWrapper on some devices:


1 - An error message could occur something about dbgeng.dll .

Fix: rename **dbghelp.dll** to something else, it's stored in \Army Men RTS\library\dbg folder.


2 - Issue where the game crashes at the startup without getting any error message.

Fix: go to **Control Panel\Hardware and Sound\Devices and Printers** , right click your device select **Properties**, on **Hardware** tab scroll down to the bottom, will find **USB Input Device** click **Properties** then **Change settings** and **Disable Device** on **Driver** tab. I think this is an uncommon issue that happens to Army Men RTS,
Commandos 2 Men of Courage and Commandos 3 Destination Berlin

**Comment by elishacloud** [comment] 2024-09-23 02:15
Very good.  Closing the issue now.

**Closed by elishacloud** 2024-09-23 02:15 UTC
