### ISSUE TITLE
Star Trek Armada no backgrounds with Intel integrated graphics Windows 11

### ISSUE THREAD

**Issue by airbornesurfer** [elishacloud/dxwrapper#153] opened 2022-07-21 02:20 UTC
Hate to pile onto the "Armada doesn't work" wagon, but I'm getting the same problem as described in https://github.com/elishacloud/dxwrapper/issues/28#issue-339708355 wherein the backgrounds during the missions aren't loading.

I'm using the fix as described in https://github.com/elishacloud/dxwrapper/wiki/Star-Trek-Armada-1, and I've tried with the assets in the zip file linked from the wiki page. I have also tried using the updated ddraw.dll and dxwrapper.dll from the latest (1.0.6542.21) release with the dxwrapper.ini settings from the wiki zip.

Everything opens and runs decently (a few hiccups here and there between the opening cutscene, menus, and mission start, but nothing affecting gameplay). The only issue is the black layer blocking all background textures in both the main screen and the mini map. Ships, planets, etc. still draw, but no grids.

1.2 retail CD release, patched to 1.3
Intel Iris Xe Graphics 30.0.101.1994 (also attempted with earlier graphics driver to no avail)
Windows 11 Pro
No compatibility settings enabled

Let me know if you need anything else for diagnosis, and thank you for all your hard work!

**Comment by elishacloud** [comment] 2022-08-23 01:51
Ok, try with the following update.  Unzip this into the Armada folder, overwriting any existing files:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/9398691/dxwrapper.zip)

**Comment by accwebs** [comment] 2023-01-01 22:39
Stumbled on this issue.  Having the same problem.  Still on Windows 10.  No luck with the above (attached) version.

For reference, a workaround is to configure 'shroud off' in the game creation settings (although this does not help with single player story mode).

**Comment by helitheone** [comment] 2023-03-26 11:42
Habe leider auch noch keine lösung gefunden ;(

**Comment by elishacloud** [comment] 2023-03-27 17:21
This might have to do with D3D9On12.  A lot of Intel systems are using that.  I need to check on this later.

**Comment by elishacloud** [comment] 2023-04-15 03:05
I tested this and it is an issue with D3D9On12.  However, I just posted an update patch that should address this issue.  You can see the update here:  [Star Trek Armada 1 patch](https://github.com/elishacloud/dxwrapper/wiki/Star-Trek-Armada-1)

**Comment by accwebs** [comment] 2023-04-16 19:27
Hey, thanks!  I'll give this a try and report back :-D

**Comment by accwebs** [comment] 2023-04-18 01:09
Darn, no dice.  (Thanks for trying though!)

Here's the log:

[dxwrapper-armada.log](https://github.com/elishacloud/dxwrapper/files/11256957/dxwrapper-armada.log)

**Comment by mirh** [comment] 2023-04-18 20:03
If it's an issue with D3D9On12, then I feel like it should be reported there. 
In the meantime, idk if Intel hasn't added a mechanism to switch back between that and their original/native/old trinity d3d9 codepath, but worst case scenario I suppose you could just use dxvk. 

p.s. a number was missed in the "patch updated" date

**Comment by accwebs** [comment] 2023-04-19 00:01
Hi @mirh ,

Thanks...it's been about 10 years since I've done any DirectX programming so I wasn't aware of a bunch of the recent developments you mentioned (D3d9On12 and DxVK).  I did some quick Googling/reading about these things and I think I understand what might be going on.  Thanks!  I'll do some tinkering!

**Comment by elishacloud** [comment] 2023-07-12 19:05
I found out the reason that the backgrounds are missing during the missions.  This game uses a rare render state type `D3DRENDERSTATE_COLORKEYENABLE` which is not implemented by some Intel video cards.

**Comment by mirh** [comment] 2023-07-12 22:06
@Squall-Leonhart was it ever eventually possible to switch between igd9trinity and d3d9on12?

**Comment by Squall-Leonhart** [comment] 2023-07-13 05:07
intel handles it all transparently and doesn't expose any controls for it.

**Comment by elishacloud** [comment] 2023-08-09 21:07
Ok, try with this update.  I have implemented the menu using GDI and the actual game play using Direct3D9.  I added a shader for D3DRENDERSTATE_COLORKEYENABLE support.

Here is the new update: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12306900/dxwrapper.zip)

**Comment by accwebs** [comment] 2023-08-10 00:21
It works!!!!

Wow, that was an unexpected surprise!

**Comment by elishacloud** [comment] 2023-08-10 02:55
Great!  Thanks for the confirmation.

**Comment by Squall-Leonhart** [comment] 2023-08-10 05:59
what intel cpu do you have accwebs, there shouldn't have been any issues with the pre-Xe/XeMax/Arc/7x0 gpus in the DCH driver, and if you have one of these but still using the DCH driver then it was your issue all along.

**Comment by elishacloud** [comment] 2023-08-11 00:07
From the dxwrapper log file here is what the graphics card is reading as:

```
8904 20:06:42.521 Intel(R) UHD Graphics
```

BTW: here are two more good discussions on color keying.  Though they are related to Nvidia it is still good info.

https://github.com/narzoul/DDrawCompat/issues/116#issuecomment-946084312
https://github.com/narzoul/DDrawCompat/issues/241#issuecomment-1671964348

**Comment by accwebs** [comment] 2023-08-11 00:09
> what intel cpu do you have accwebs, there shouldn't have been any issues with the pre-Xe/XeMax/Arc/7x0 gpus in the DCH driver, and if you have one of these but still using the DCH driver then it was your issue all along.

11th Gen Intel Core i9-11900H.  It's a laptop in case that matters (idk if Intel is still doing their 'mobile vs desktop edition' thing they used to do without giving the processors a unique product number despite the difference).

**Comment by Squall-Leonhart** [comment] 2023-08-11 05:13
The IGP in the Tigerlake-H is an Xe variant, so it is supported by the Arc and Iris drivers.

With the DCH variant, you're stuck using 9on12, which is the cause of the issue with DXWrapper

**Comment by mirh** [comment] 2023-08-11 13:48
I thought both the Arc and GCC drivers were DCH-based?

**Comment by Squall-Leonhart** [comment] 2023-08-11 14:20
> I thought both the Arc and GCC drivers were DCH-based?

They are, but Intel maintains DCH in the title and filename of the old driver that includes the 9on12 implementation for Iris/Xe parts it supports, and drops DCH from the title and file name of the Iris and Arc Xe package.

**Comment by elishacloud** [comment] 2023-08-11 15:05
> With the DCH variant, you're stuck using 9on12, which is the cause of the issue with DXWrapper

9on12 is not an issue with dxwrapper.  The issue happens without dxwrapper.  There are several fixes in dxwrapper for cards that use 9on12.

**Comment by Squall-Leonhart** [comment] 2023-08-11 15:45
> 9on12 is not an issue with dxwrapper. The issue happens without dxwrapper. There are several fixes in dxwrapper for cards that use 9on12.

The capabilities of D3D8, DDraw and D3DImm are directly tied to the D3D9 capabilitys of the hardware and its driver, the D3D9 UMD and DX runtime in combination handle emulation of the fixed function capabilities, including those going back to the legacy DDraw D3D primitives and the colour combiner caps provided in D3D8, this is why some Drivers are better than others for legacy games with less than 32/24 bit formats.

The issue is going to happen whether you use dxwrapper or not for obvious reasons, the capabiltiy just isn't exposed by the driver with the Iris and Xe parts because it doesn't have a true legacy DX UMD, just an emulation layer.

**Comment by elishacloud** [comment] 2023-08-11 15:58
Yes, I understand.  dxwrapper has a feature to convert the game from DDraw/Direct3D or d3d8 to d3d9.  So functions like D3DRENDERSTATE_COLORKEYENABLE need to be re-implemented on d3d9.  In this case, since d3d9 does not have this function I use shaders to emulate it.

**Comment by Squall-Leonhart** [comment] 2023-08-11 16:13
Makes sense for a promotion to D3D9 vs keeping it on D3D8, D3DRENDERSTATE_COLORKEYENABLE is definitely not a d3d9type.

**Comment by mirh** [comment] 2023-08-13 17:03
Just for the records (after banging my head a little on the topic) I think one better way to frame the issue is simply that Xe drivers *anywhere* before 31.0.101.3959 didn't ship igd9trinity. 
Because "DCH" hasn't been [updated](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) since october last year (except perhaps [this](https://www.intel.com/content/www/us/en/download/762755/intel-6th-10th-gen-processor-graphics-windows.html) for old cpus, but build number is still quite lower), so of course it couldn't ship anything better. Also of note that for a [very short time](https://web.archive.org/web/20221215000000*/https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html) "Arc DCH" was also a thing.

**Comment by elishacloud** [comment] 2023-10-03 21:54
This issue should be fixed with the latest update here:  https://github.com/elishacloud/dxwrapper/wiki/Star-Trek-Armada-1

**Closed by elishacloud** 2023-10-03 21:54 UTC
