### ISSUE TITLE
BloodRayne 2

### ISSUE THREAD

**Issue by Keith94** [elishacloud/dxwrapper#7] opened 2017-08-22 21:48 UTC
Sorry if this is the wrong place to post, but I couldn't find a solution elsewhere yet.

There exists an unofficial "FSAA Patch" that adds new features to the game.

[BR2 FSAA Patch 1.666.zip](https://github.com/elishacloud/dxwrapper/files/1243438/BR2.FSAA.Patch.1.666.zip)

However with the patch installed it crashes the game on startup. The developer [commented](https://steamcommunity.com/app/3820/discussions/0/535152276585406170/#c517141624286794292) that it's a problem with a Windows 10-specific call:

>IDirect3D8::CreateDevice(Adapter: 0, DeviceType: 1, hFocusWindow: 2165074, BehaviorFlags: 66|D3DCREATE_FPU_PRESERVE|D3DCREATE_HARDWARE_VERTEXPROCESSING, PresentationParameters: (0x00A013F4BackBufferWidth: 2560, BackBufferHeight: 1440, BackBufferFormat: D3DFMT_X8R8G8B8, BackBufferCount: 1, MultiSampleType: 4, SwapEffect: D3DSWAPEFFECT_DISCARD, hDeviceWindow: 2165074, Windowed: false, EnableAutoDepthStencil: true, AutoDepthStencilFormat: D3DFMT_D24S8, Flags: NONE, FullScreen_RefreshRateInHz: D3DPRESENT_RATE_DEFAULT, FullScreen_PresentationInterval: D3DPRESENT_INTERVAL_IMMEDIATE), ReturnedDeviceInterface: 0x00000001)

I'm on Windows 8 and I also tried the workarounds detailed in that thread (disabling AA color samples/enabling MSAA externally etc.) to no avail. Is there anything I missed or any insight on how to use this patch that you know of? Thanks.

**Comment by elishacloud** [comment] 2017-08-23 06:17
It looks like the issue is with Anti-Aliasing.  Have you tried disabling Anti-Aliasing or setting the "AA Color Samples" to '0'?

Also I made a quick update to the patch.  I don't have _BloodRayne 2_ so I could not test it.  Let me know if this works or not.  Basically this patch does two things:
1. Converts Direct3D8 to Direct3D9.
2. Tests Anti-Aliasing and sets the highest supported mode.  If no Anti-Aliasing is supported it disables Anti-Aliasing.

[BR2.FSAA.Patch.1.666-Updated.zip](https://github.com/elishacloud/dxwrapper/files/1244328/BR2.FSAA.Patch.1.666-Updated.zip)

**Comment by Keith94** [comment] 2017-08-23 18:48
Hi @elishacloud and thanks for the support.

Yes, I made sure to turn off AA color samples in the config tool. But it did not solve the crashing issue. :(

I tested your updated patch also but I get the same results. If you're interested I can link you the GOG installer for the game for better testing.

**Comment by elishacloud** [comment] 2017-08-24 20:06
I did purchase the game on [GOG](https://www.gog.com/game/bloodrayne_2) (interesting game!). This issue with Windows 10 is much larger than just what is mentioned on that thread.

1. It is pretty easy to bypass the AA issue (and send MultiSampleType of '0').
2. Also it is not too hard to 'patch' this dll so that it can be used with a Direct3D8 to Direct3D9 converter.

However there seems to be a third issue with unofficial "FSAA Patch" that makes is crash on Windows 10.  I am not sure what this third issue is.

There are [comments](https://steamcommunity.com/app/3820/discussions/0/535152276585406170/?ctp=2#c485624149156113270) on the thread that says there is "some kind of data structure ... [but] the memory used by this structure gets obliterated with text midway through the function and corrupts the data structures."  The patch may be using hard coded memory addresses and these addresses could be in a different location in Windows 10 compared to other versions of Windows.  I need more time to investigate this.

I suspect the issue is with some Direct3D call that is changed in Windows 10.

**Comment by Keith94** [comment] 2017-08-25 01:56
Interesting, well I do experience the same startup crashes on Windows 8, so I'm not sure if my issue is related to that. Looking forward of your findings anyhow.

**Comment by elishacloud** [comment] 2017-09-09 03:52
Hello Keith,

I think I figured out the issue.  It had to do with the VertexShader instruction count.  It seems that [d3d8to9](https://github.com/crosire/d3d8to9) was adding too many extra instructions and causing the shader assembly to fail.  See this site [here](https://reshade.me/forum/troubleshooting/973-bloodrayne-bloodrayne-2) for more details.

The fix was relatively straight forward.  I reduced the number of extra instructions that needed to be added and I made sure that the critical ones got added first.

Here is the update: [BR2.FSAA.Patch.1.666 Fix v1.zip](https://github.com/elishacloud/dxwrapper/files/1289521/BR2.FSAA.Patch.1.666.Fix.v1.zip)

Just make sure that all your compatibility settings are disabled.  It does not seem to work if any compatibility settings are turned on.  At least it did not work for me.

![compatibility](https://user-images.githubusercontent.com/25625456/30236801-5f23ce54-94d7-11e7-903f-c3ffc765e887.png)

**Comment by Keith94** [comment] 2017-09-09 08:27
Awesome, that fixed the crashing issue. I didn't know d3d8to9 by itself could do it.

Btw if AA Color Samples is set above 8, it will still crash, but at least it works fine now. Thanks for the update!

**Comment by elishacloud** [comment] 2017-09-09 16:09
> if AA Color Samples is set above 8, it will still crash, but at least it works fine now. Thanks for the update!

Yes, this is an issue with the BloodRayne 2 FSAA Patch 1.6 itself.  The patch does not have very good error checking.  Setting the wrong options for your system can cause it to crash.  I doubt your video card supports anything over AA 8 anyways.

I am going to go ahead and close this since the core issue has been fixed.

**Closed by elishacloud** 2017-09-09 16:09 UTC

**Comment by elishacloud** [comment] 2017-11-25 07:31
I posted the code for this fix on GitHub:  [BloodRayne-2-Patch](https://github.com/elishacloud/BloodRayne-2-Patch)

**Comment by Keith94** [comment] 2017-11-25 20:25
Nice dude! Thanks for that.

**Comment by elishacloud** [comment] 2018-04-26 02:02
@justm34evah, I assume you are using a laptop with an integrated Intel and Nvidia graphics card?  It seems like the GPU's on these laptops are limited and do not support all of the required functions.  This issue might be similar to the issue with Start Trek Armada 1 seen on [fleetops.net](https://www.fleetops.net/forums/armada/armada-1-in-windows-10-12841?p=205906#p205906).

I probably need to figure out which functions are not available and rewrite them.  I am not sure when I will have time to look at this, but you are welcome to open a new issue on this.

**Comment by justm34evah** [comment] 2018-04-26 08:43
Yes, that is completely true. A laptop with both, and I can't disable the
integrated graphics card... Well, for now I'll stick to dgvoodoo2 and
wide-screen, but the FSAA on Nvidia would have so much better
performance...please look into this matter whenever you have the time. A
patch update for ppl like me would be great :). Should I open a new thread?

**Comment by mirh** [comment] 2018-04-26 10:35
I have some information about optimus and <D3D9 [here](https://pcgamingwiki.com/wiki/User_talk:Garrett/Troubleshooting/Windows_10).

**Comment by justm34evah** [comment] 2018-04-26 11:30
Silly optimus. Whoever came up with it? Jesus these people.

**Comment by mirh** [comment] 2018-04-26 16:03
Smart engineers trying to make the best of both worlds. 
For some reason though, <D3D9 was left out. 

@ataulien did you ever figured out if this choice(?) was technical, laziness or else?

**Comment by justm34evah** [comment] 2018-04-26 16:35
Why not let me choose what video card I want, why does optimus have to
force my answer to save battery life. Maybe I do not want that. I don't
understand this concept at all. Nvidia should get their shait together.

**Comment by elishacloud** [comment] 2018-04-26 18:36
http://www.vogons.org/viewtopic.php?f=8&t=45661#p459344

> if you have a laptop with Nvidia Optimus and you try to run a game that uses DX1-8, it always runs on Intel GPU

http://nvidia.custhelp.com/app/answers/detail/a_id/3733

>Games based on DirectX 8 and older versions of DirectX will only run on integrated graphics in an Optimus laptop

@mirh, these articles seem to be talking about D3D8 and older.  Are you saying that D3D9 also does not work with Optimus?

**Comment by justm34evah** [comment] 2018-04-26 18:50
Dx9 and later use Dedicated cards.

**Comment by mirh** [comment] 2018-04-26 19:25
? Isn't BloodRayne d3d8?

**Comment by justm34evah** [comment] 2018-04-26 19:53
Yes, testing it now using dgvoodoo2 emulator. Quite a few fps drops using
my gtx 1070...if only I could force it to run on the dedicated card without
an emulator...the original FSAA patch works great for me, no crash, but
it's forcibly run using my Intel gt630 so it has extremely poor
performance...

**Comment by elishacloud** [comment] 2018-04-26 22:29
dgVoodoo just converts this to DirectX 11.

My patch converts it to DirectX 9.  This is why Optimus opens it up using your Nvidia GTX 1070.  I think the "graphical glitches and misaligned stuff" comes because the Nvidia card has a bunch of missing/unsupported functions.

**Comment by justm34evah** [comment] 2018-04-26 22:33
True. If you could look into this matter for me, that would be really
appreciated. Like, I installed dx9, maybe I need a certain c++ or version
of directx
