### ISSUE TITLE
Any plan for an update?

### ISSUE THREAD

**Issue by Mitch037** [elishacloud/dxwrapper#210] opened 2023-07-26 14:08 UTC
Hello @elishacloud,
The last release of dxwrapper took place over 2 years ago. Numerous wrappers which are part of dxwrapper have been updated since that time (e.g. D3D8TO9). Do you plan to update it?

**Comment by elishacloud** [comment] 2023-07-26 18:49
Yes, I am working on an update to be released soon.

**Comment by elishacloud** [comment] 2023-08-09 20:47
The video card on my computer died and it will take longer to finish the testing.  I plan to release an update before the end of the year.

**Comment by elishacloud** [comment] 2023-08-09 20:54
Duplicate of #173

**Closed by elishacloud** 2023-08-09 20:54 UTC
