### ISSUE TITLE
Update Release

### ISSUE THREAD

**Issue by Mitradis** [elishacloud/dxwrapper#173] opened 2023-03-12 18:36 UTC
Update Release pls. I downloaded and for a long time could not understand why I did not have new features, until I realized that I had downloaded the old version.

**Comment by Mitradis** [comment] 2023-03-12 21:50
Dd7to9 and DDrawCompat can work together?

**Comment by elishacloud** [comment] 2023-03-13 20:30
> with Dd7to9 in Space Rangers 2 Dominators not run planet battle.

Ok, this is something I will need to look at later.

> Boot screen saver won't go away.

Are you saying that the screensaver sometimes comes on when playing a game?  I should be able to turn this off.

> With only EnableDdrawWrapper game not run.

Could be a bug in the wrapper.

> Why new version not in Release page.

I have several dozen games I test before releasing a new build.  This process can take a while and I have not had time to do that yet.

> With DDdrawCompat work.

If DDdrawCompat works, why not just use that?

**Comment by Kim2091** [comment] 2023-04-21 18:52
Could Github CI be set up and built daily with Actions?

**Comment by elishacloud** [comment] 2023-08-09 20:54
> Could Github CI be set up and built daily with Actions?

CI was setup.  But I don't always change the build each day.

The video card on my computer died and it will take longer to finish the testing. I plan to release an update before the end of the year.

**Comment by elishacloud** [comment] 2023-08-09 21:13
Duplicate of #152.

**Closed by elishacloud** 2023-08-09 21:13 UTC
