### ISSUE TITLE
Zoo Tycoon Complete Collection crashes/don't work (D3D7)

### ISSUE THREAD

**Issue by LuKeSt0rm** [elishacloud/dxwrapper#305] opened 2024-10-13 18:07 UTC
Game no longer responds after alt+tab and crashes. (Dd7to9)

- Dd7to9=1
- DdrawWriteToGDI=1 (0=freezes in loading screen)
- FullscreenWindowMode=1 (0=game window will be displayed in the top left in it's original game resolution and will freeze in loading screen)

I have also tried several other options. Game works with DDrawCompat.

[dxwrapper-zoo.log](https://github.com/user-attachments/files/17356604/dxwrapper-zoo.log)

**Comment by elishacloud** [comment] 2024-10-30 23:37
I am not quite sure what is causing the issue.  The logs don't have any useful data and I may need to try and reproduce this issue

I did put a couple recent fixes that might resolve the issue.  You may want to check with the latest build and let me know if there is still an issue.

**Comment by LuKeSt0rm** [comment] 2024-10-31 01:32
Nothing changed

**Comment by elishacloud** [comment] 2024-10-31 22:19
Instead of using `FullscreenWindowMode` try setting `SetSwapEffectShim` or `DisableMaxWindowedMode`.  There are a couple of games, namely Command & Conquer games, that will not show anything and appear to freeze without enabling `SetSwapEffectShim`.

**Comment by LuKeSt0rm** [comment] 2024-10-31 22:31
I tried the options `SetSwapEffectShim` and `DisableMaxWindowedMode` = stuck in the loading screen

**Comment by LuKeSt0rm** [comment] 2024-11-01 13:42
Here the demo of zoo tycoon (in case you need it) 
https://archive.org/download/zootycoondemo/ZooTycoon.exe

**Comment by elishacloud** [comment] 2024-11-02 00:50
> Here the demo of zoo tycoon (in case you need it) https://archive.org/download/zootycoondemo/ZooTycoon.exe

Thanks!  I will take a look at it when I get a chance.

**Comment by elishacloud** [comment] 2024-11-07 22:27
I believe this is the issue:

```log
7180 14:24:30.696 m_IDirectDrawSurfaceX::UpdateOverlay Error: Not Implemented
```

I have not added support for the Overlay yet.  In fact, this is one of the first games I have seen that use it.

**Comment by elishacloud** [comment] 2024-11-07 22:51
Ok, I was able to get the game working by:

1. Enabling only `LockEmulation` and `EnableOverlays`
2. Running the game as an Admin

![image](https://github.com/user-attachments/assets/0f7f5120-5041-49c9-ba78-6a3c9e20130b)

Here is the build with the correct settings:  [dxwrapper.zip](https://github.com/user-attachments/files/17670342/dxwrapper.zip)

Later I will add support for the `UpdateOverlay()` fucntion and get this game working with `dd7to9`.

**Comment by elishacloud** [comment] 2024-11-08 00:29
Ok, I figured out the issue.  The game is set to run in exclusive fullscreen mode.  In this mode the game hangs when Windows tries to send certain messages to the game.  I added code to filter out those messages in this case.

Here is the updated fixed build:  [dxwrapper.zip](https://github.com/user-attachments/files/17670973/dxwrapper.zip)

_Note: I still need to figure out why the game does not work without enabling `DdrawWriteToGDI` and `FullscreenWindowMode`.  But I will work on that later._

**Comment by elishacloud** [comment] 2024-11-08 02:11
The latest build should work without enabling `FullscreenWindowMode`.  This will allow you to switch between fullscreen and windowed mode in-game.  The game may be using a combination of GDI and DirectDraw, which may be why `DdrawWriteToGDI` is required.

Here is the latest build:  [dxwrapper.zip](https://github.com/user-attachments/files/17671660/dxwrapper.zip)

_This build should work with only `dd7to9` and `DdrawWriteToGDI` enabled._

**Comment by LuKeSt0rm** [comment] 2024-11-08 10:58
Thanks awesome, now works without `FullscreenWindowMode`

There's just one more issue: 
If you use "Immediate" option at "Terrain Blending" under Game options -> "Sound & Video", certain textures are just black. As you can see on the screenshot. It also requires `DdrawEmulateSurface` so that the game doesn't crash when loading savegame, for example.

`DdrawEmulateSurface` option disabled - log:
> m_IDirectDrawSurfaceX::Lock2 Error: failed to lock surface. Is Texture. Size: 64x64 Format: D3DFMT_A8R8G8B8 Flags: 0x810 Locked: 0 DC: 0 Blt: 0 hr: D3DERR_INVALIDCALL

![textureissue](https://github.com/user-attachments/assets/d9d68a01-0e8b-4799-a711-2be0a3ae7331)

**Comment by elishacloud** [comment] 2024-11-08 21:28
> If you use "Immediate" option at "Terrain Blending" under Game options -> "Sound & Video", certain textures are just black.

I cannot reproduce this issue.  The demo version does not have this issue.  But this may be related to another issue I have seen where some textures stay black on certain texture.  I have seen this with several other games so far.  Not sure what is happening though.  You could try enabling `DdrawForceMipMapAutoGen`.  In some cases this helps with missing textures.

> It also requires `DdrawEmulateSurface` so that the game doesn't crash when loading savegame, for example.

I put a change in to try and prevent the game from crashing when the Lock fails.  Not sure if this will fix the issue, but you shouldn't need to have `DdrawEmulateSurface` enabled with this update:  [dxwrapper.zip](https://github.com/user-attachments/files/17684182/dxwrapper.zip)

**Comment by LuKeSt0rm** [comment] 2024-11-09 14:25
> I cannot reproduce this issue. The demo version does not have this issue. But this may be related to another issue I have seen where some textures stay black on certain texture. I have seen this with several other games so far. Not sure what is happening though. You could try enabling `DdrawForceMipMapAutoGen`. In some cases this helps with missing textures.

`DdrawForceMipMapAutoGen` doesn't help in this case
> I put a change in to try and prevent the game from crashing when the Lock fails. Not sure if this will fix the issue, but you shouldn't need to have `DdrawEmulateSurface` enabled with this update: [dxwrapper.zip](https://github.com/user-attachments/files/17684182/dxwrapper.zip)

`DdrawEmulateSurface` still needed

**Comment by elishacloud** [comment] 2024-11-10 06:48
I was able to reproduce the game crash on load.  It's not actually a crash.  The game exits when the Lock() function returns anything but OK.  Anyways, I found the issue.  Try this build:  [dxwrapper.zip](https://github.com/user-attachments/files/17690484/dxwrapper.zip)

As far as the black textures, for me the whole screen turns black.  However, if I Alt+Tab out of the game and then click to restore the game window then the textures reappear.  I will look into this issue soon.

**Comment by LuKeSt0rm** [comment] 2024-11-10 13:56
> I was able to reproduce the game crash on load. It's not actually a crash. The game exits when the Lock() function returns anything but OK. 
works now, thanks :)

**Comment by elishacloud** [comment] 2024-11-12 03:10
Ok, I think I figured out the black screen issue.  Here is the latest build, I am hoping this fixes all the issues with the game:  [dxwrapper.zip](https://github.com/user-attachments/files/17710591/dxwrapper.zip)

Note: you still need to have `DdrawWriteToGDI` to see the menu because it appears the the menu is made via GDI.  I don't think there is much I can do about that.

**Comment by LuKeSt0rm** [comment] 2024-11-12 09:58
> Ok, I think I figured out the black screen issue. Here is the latest build, I am hoping this fixes all the issues with the game:

With `DdrawForceMipMapAutoGen` and `FullscreenWindowMode` option enabled it works now.



> Note: you still need to have `DdrawWriteToGDI` to see the menu because it appears the the menu is made via GDI. I don't think there is much I can do about that.

No problem at all, it works.

Thanks!

**Comment by elishacloud** [comment] 2024-11-15 04:25
> With `DdrawForceMipMapAutoGen` and `FullscreenWindowMode` option enabled it works now.

That is weird.  I am using the demo version but I don't need to have either of those options enabled.  Everything works fine if I just enable `DdrawWriteToGDI`.  What are all of the options you have enabled and what are each of the options required for?

**Comment by LuKeSt0rm** [comment] 2024-11-15 11:19
I have now tested it again: Complete version has this issue. (demo works fine)

**Comment by elishacloud** [comment] 2024-11-16 03:20
> Found way to reproduce: `zoodemo.ini` -> `playMovie ` to `0` or delete movie files.

Thanks for the steps to reproduce the issue.  I think I fixed it.  Try this one:  [dxwrapper.zip](https://github.com/user-attachments/files/17783246/dxwrapper.zip)

**Comment by elishacloud** [comment] 2024-11-16 14:45
While the latest build (here's an update: [dxwrapper.zip](https://github.com/user-attachments/files/17786752/dxwrapper.zip)) fixes the missing textures in most cases, I found one case where there are still missing textures:

Steps:
1. Start the game.
2. Switch modes from fullscreen to windowed, or vice versa.
3. After switching modes rotating the game map, and missing textures will appear.

_Note: a work around is to rotate the game map all the way around (4 times) before switching modes and the textures will not disappear._

**Comment by LuKeSt0rm** [comment] 2024-11-16 15:15
Thanks, it now works without `FullscreenWindowMode`
Found something else strange: 
if you use the current desktop resolution (e.g. 1920x1080) in the ini, the black textures are back. (works without wrapper)

**Comment by elishacloud** [comment] 2024-11-22 05:55
> Btw: Do I see correctly loading the d3d8.dll via loadlibrary of the game is actually unnecessary?

Correct, you shouldn't need to load any extra dlls.  I checked and the game doesn't use Direct3D8 so you shouldn't need to load d3d8.dll.

> if you set current desktop resolution (e.g. 1920x1080) in game ini (screenwidth, screenheight), black textures are back.

Ok, I put in a fix for this.  Here is the fix for this issue:  [dxwrapper.zip](https://github.com/user-attachments/files/17865068/dxwrapper.zip)

_Note: There is still an issue if you change resolutions in game or change modes (windowed vs. fullscreen) and then rotate the map.  I will try and fix that later._

**Comment by LuKeSt0rm** [comment] 2024-11-22 18:04
It works perfectly fine now, thank you very much!

**Comment by elishacloud** [comment] 2024-11-22 20:52
Very good.  I will fix the rest later.  That will require a bit more work.

**Comment by elishacloud** [comment] 2024-12-03 00:29
Ok, here is the final fix.  This should fix all cases where textures turn black.

New build:  [dxwrapper.zip](https://github.com/user-attachments/files/17985388/dxwrapper.zip)

**Comment by LuKeSt0rm** [comment] 2024-12-03 17:34
Works like a charm, finally done - thanks!

**Comment by elishacloud** [comment] 2024-12-03 18:44
I found a coding error in the last build that could cause a crash.  I recommend using this build instead:  [dxwrapper.zip](https://github.com/user-attachments/files/17997557/dxwrapper.zip)

**Comment by LuKeSt0rm** [comment] 2024-12-03 20:25
Loading progress is invisible and if you go back to the main menu from running game, last frame appears as image in background.

Issue occurs with commit [#c7aa904](https://github.com/elishacloud/dxwrapper/commit/c7aa904c2f20abea851acf2615907014e0535edf)  (Add partial support for UpdateOverlay)

**Comment by LuKeSt0rm** [comment] 2024-12-03 22:29
Works fine now

**Closed** 2024-12-04 02:02 UTC
