### ISSUE TITLE
Twisted Metal 2

### ISSUE THREAD

**Issue by LuKeSt0rm** [elishacloud/dxwrapper#85] opened 2020-09-20 09:47 UTC
Hello :)
With Direct3D the texts are not displayed in the input options and the multiplayer menu. 
Screenshots: https://i.imgur.com/K5AKoPI.png | https://i.imgur.com/LMK8348.png

Gameplay works very well, even the menu works with the felt right speed with "EnableVSync".
Should I try to compile a new build of dxwrapper or you already have a new build I can try ?

**Controller/Joystick** (This following problem is independent of dxwrapper)
The game recognizes controllers such as the Xbox controller and you can also change the buttons and they work.

But you can't execute the combos like jump, shield, ice rocket with the corresponding combination of up, right, down, left in game, but with the arrow keys it works. I wonder why it is that driving works, only the combos do not. Maybe an idea?

**Comment by elishacloud** [comment] 2020-09-21 07:53
Hello,

> With Direct3D the texts are not displayed in the input options and the multiplayer menu.

It is possible that this is caused because of GDI.  GDI is not available when using fullscreen Direct3D9.  Try using the previous build I gave you and enabling the `FullscreenWindowMode`.

> Gameplay works very well, even the menu works with the felt right speed with "EnableVSync".

Yes, the gameplay should always be at the right speed with `EnableVSync` because the timing is controlled by the video card.

> Should I try to compile a new build of dxwrapper or you already have a new build I can try ?

No, you should not need to compile it yourself, unless you want to.  I don't have any newer builds that would help you.

> The game recognizes controllers such as the Xbox controller ... But you can't execute the combos like jump, shield, ice rocket with the corresponding combination of up, right, down, left

I am not sure the issue here.  I will try and look into it this week and see what is happening.

**Comment by Canno** [comment] 2020-09-21 12:46
> It is possible that this is caused because of GDI. GDI is not available when using fullscreen Direct3D9. Try using the previous build I gave you and enabling the `FullscreenWindowMode`.

It's working, but only felt 5 FPS in-game with or without "FullscreenWindowMode".
[dxwrapper-tm2.log](https://github.com/elishacloud/dxwrapper/files/5255401/dxwrapper-tm2.log)

**Comment by mirh** [comment] 2020-09-21 16:39
***IIRC*** shitty GDI performance was linked to the lack of DXMaximizedWindowedMode...
Which on W10 is always on now, causing other problems unless you hack off Direct3D8EnableMaximizedWindowedModeShim...
...
Did you try to fiddle with `DXPrimaryEmulation` options?

**Comment by elishacloud** [comment] 2020-11-17 04:01
Twisted Metal 2 should be fixed with the latest build when using `Dd7to9`.

Here is the updated build:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/5549441/dxwrapper.zip)

**Comment by elishacloud** [comment] 2023-04-12 21:23
Closing issue.

**Closed by elishacloud** 2023-04-12 21:23 UTC

**Comment by elishacloud** [comment] 2024-11-12 04:47
Here is a better fix for this game: [dxwrapper.zip](https://github.com/user-attachments/files/17711240/dxwrapper.zip)

**Comment by LuKeSt0rm** [comment] 2024-11-12 14:14
Works in Direct3D mode of the game.  In the weapon selection menu (bottom right) in-game are artifacts/is distorted.
![guidisplayissues](https://github.com/user-attachments/assets/3575631e-1b22-4bc9-aef2-497c55b8905d)

**Comment by elishacloud** [comment] 2024-11-14 22:17
> In the weapon selection menu (bottom right) in-game are artifacts/is distorted.

That is caused by either the `AnisotropicFiltering` or `AntiAliasing`.  Probably the former.  Disable those and it will look normal.
