### ISSUE TITLE
Command & Conquer: Generals – Zero Hour

### ISSUE THREAD

**Issue by archibald1337** [elishacloud/dxwrapper#286] opened 2024-07-28 20:18 UTC
First of all I want to thank you for your project. Using it I've managed to fix unlimited framerate of the game on Windows 11 which was a source of broken animations of some objects and too fast movement of scrolling the map.

Now I'm working on some other fixes of the game:
1. **Broken Alt+Tab**. It happens on Windows 8 and later versions. My current fix is to launch the game as a fullscreen window and then removing the style WS_EX_TOPMOST which prevents the game window from switching between other windows. It boils down to the next code:
```
        SetWindowLongW(hwnd, GWL_EXSTYLE, GetWindowLong(hwnd, GWL_EXSTYLE) & -WS_EX_TOPMOST);
        SetWindowPos(hwnd, HWND_NOTOPMOST, 0, 0, resolution.width, resolution.height, **SWP_FRAMECHANGED);
```

2. **Remapping WASD keys to ↑←↓→ keys**. This one is more trickier, I need to inject a DLL or run another program and set up a hook and change aforementioned keys at right time when game match is started. This one is in progress. There is also a way to do it via AutoHotKey but I want to gather these fixes in one program.

So, my overall questions are: is there any functionality in the dxwrapper allowing me to change the style of the window?
And, is there any way to inject my own code?

**Comment by archibald1337** [comment] 2024-07-29 17:56
elishacloud, thanks for your fast reply! I've downloaded and launched the latest build.
Unfortunately, calling SetWindowPos with SWP_NOZORDER flag prevents from removing class WS_EX_TOPMOST ([link to the docs](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos) so this one doesn't work:

```
SetWindowPos(DeviceDetails.DeviceWindow, ((lExStyle & WS_EX_TOPMOST) ? HWND_NOTOPMOST : HWND_TOP), 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED);
```

I've tested without SWP_NOZORDER and it worked as needed, removing the class:

```
SetWindowPos(DeviceDetails.DeviceWindow, ((lExStyle & WS_EX_TOPMOST) ? HWND_NOTOPMOST : HWND_TOP), 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_FRAMECHANGED);
```


I'm not sure how it must be added to your library so not to break support of other games etc.
Maybe it's a good idea to break removing WS_EX_TOOLWINDOW and WS_EX_TOPMOST classes into to separate calls of SetWindowLong+SetWindowPos?

Also, maybe it's should be enabled some option?

**Comment by elishacloud** [comment] 2024-07-30 01:17
Good catch!  I fixed it.  I tested with a few games.  I don't think it will cause an issue.  But there could be other games that have the same issue as Command & Conquer: Generals Zero Hour so for now I'll just make it standard.  I can always change it later if I find an issue with another game.

You can test it here:  https://github.com/elishacloud/dxwrapper/actions/runs/10154381394

**Comment by archibald1337** [comment] 2024-07-30 01:46
Hooray, it works now like a charm!
Yes now I can retire my utility program to modifying game window and switch to your amazing dxwrapper.

Since it works perfectly, I suggest you to add Command & Conquer: Generals – Zero Hour on the list of Compatible Games. I can make a pull request describing problems with launching the game on Windows 11 and configuration of dxwrapper to fix them.

**Comment by elishacloud** [comment] 2024-07-30 01:53
> Hooray, it works now like a charm!

Ok, great.

> Since it works perfectly, I suggest you to add Command & Conquer: Generals – Zero Hour on the list of Compatible Games. I can make a pull request describing problems with launching the game on Windows 11 and configuration of dxwrapper to fix them.

Sure.  Feel free to make a pull request.  I am not that good at updating the documentation.  Thanks!

**Comment by archibald1337** [comment] 2024-07-30 14:36
Okay I've got i little problem with cloning wiki repo on Windows haha

```
error: invalid path 'Conquest:-Frontier-Wars.md'
error: invalid path 'Creatures-2:-The-Albian-Years.md'
error: invalid path 'Final-Liberation:-Warhammer-Epic-40,000.md'
```

**Comment by elishacloud** [comment] 2024-07-31 20:16
Those are readme pages for those games.  I have never tried creating a PR for those items, so I am not sure what the issue is.

**Comment by archibald1337** [comment] 2024-08-02 01:11
git can't checkout a revision with files containing semicolons. Could you rename them?

**Comment by elishacloud** [comment] 2024-09-23 03:32
Closing this as issue resolved.

**Closed by elishacloud** 2024-09-23 03:32 UTC

**Comment by bsimmo** [comment] 2024-12-25 10:51
> Hooray, it works now like a charm! Yes now I can retire my utility program to modifying game window and switch to your amazing dxwrapper.
> 
> Since it works perfectly, I suggest you to add Command & Conquer: Generals – Zero Hour on the list of Compatible Games. I can make a pull request describing problems with launching the game on Windows 11 and configuration of dxwrapper to fix them.

Did you do this, I can't find the details

**Comment by elishacloud** [comment] 2024-12-25 14:31
I added the game to here:  https://github.com/elishacloud/dxwrapper/wiki/Compatible-Games

**Comment by archibald1337** [comment] 2024-12-26 02:29
I haven't written a wiki page, but here's a short guide to make this work:


Copy dxwrapper.asi, dxwrapper.dll, dxwrapper.ini to the game folder, then change options:

**dxwrapper.ini**
```
[Compatibility]
D3d8to9                    = 1

[d3d9]
EnableVSync                = 1
SetInitialWindowPosition   = 1
```

And then execute Generals.exe with arguments **-win -xres 1920 -yres 1080** (or other resolution)
