### ISSUE TITLE
The ddraw.dll in the game folder is being ignored on Win10 1909

### ISSUE THREAD

**Issue by adrianer** [elishacloud/dxwrapper#64] opened 2020-04-02 19:12 UTC
The ddraw.dll (together with dxwrapper.dll and dxwrapper.ini) I've placed in the game folder is being ignored on Win10 1909 - at least it seems to have no effect and also no dxwrapper-exename.log file gets created. The same game + dll combination works on a Win7 installation without a problem... Is there a way to make the game "eat it" on the newest Win10?

The game is: The Settlers 3 from GoG

**Comment by elishacloud** [comment] 2020-04-03 22:09
The Settlers 3 uses DirectX 6.  However, it loads ddraw.dll via COM component.  See [this thread](https://github.com/narzoul/DDrawCompat/issues/18#issuecomment-320529720) for more details.  With Windows 10 when you load ddraw.dll this way it will always load it from the System32 folder.

The work around is to rename the `ddraw.dll` in dxwrapper to something else.  For this particular game you can use `dsound.dll` instead.  However, when I tested this it appears that dxwrapper has some issues with this game for some reason.  I will have to take a look at it later.

**Comment by nathanielcwm** [comment] 2021-09-30 11:46
Same issue with Settlers 4. But the log files are created.

[ddraw.log](https://github.com/elishacloud/dxwrapper/files/7259175/ddraw.log)
[dxwrapper-s4_main.log](https://github.com/elishacloud/dxwrapper/files/7259176/dxwrapper-s4_main.log)

**Comment by Seroczynski** [comment] 2022-01-23 18:12
Seems the issue is also present with Settlers IV Gold Edition from GOG when using Windows 11 Pro 21H2 22000.434.

**Comment by elishacloud** [comment] 2024-05-12 22:57
Closing issue.

**Closed by elishacloud** 2024-05-12 22:57 UTC
