### ISSUE TITLE
Balls of Steel - option to hide cursor

### ISSUE THREAD

**Issue by Omni4** [elishacloud/dxwrapper#296] opened 2024-09-07 19:56 UTC
Hi Elisha, first of all: thanks for your wrappers!

I use dxwrapper (Dd7to9 & ForceDirect3D9On12) on Balls of Steal (GOG version) and it works like a charm, except for one thing: The cursor in the center of the screen (the cursor should not be there).
I've tried dinputto8 and it lets me move the cursor to the side, but it adds a nasty long exit of the tables and I still have to move the cursor every time I start a table.
Can you please add a "hide cursor" option to dxwrapper?

Greetings,
Omni4

**Comment by elishacloud** [comment] 2024-09-07 21:40
That doesn't sound right.  What build of dxwrapper are you using?  Can you upload your logs?

**Comment by Omni4** [comment] 2024-09-07 21:45
I'm using the latest build. Here are 2 logs:
[dxwrapper-barbarin.log](https://github.com/user-attachments/files/16920015/dxwrapper-barbarin.log)
[dxwrapper-duke.log](https://github.com/user-attachments/files/16920016/dxwrapper-duke.log)

**Comment by Omni4** [comment] 2024-09-07 22:00
Just discovered that the launcher that GOG use to launch Balls of Steal is the "BOS Loader v1.0" which is "inspired by the DirectDraw wrapper project".
The default bos.exe does not have the cursor problem, but the launcher is stuck in the top left of the screen.
I've also tested BOS Loader v1.1 and it gives the same cursor problem with a loading cursor.

**Comment by elishacloud** [comment] 2024-09-07 22:45
Can you try with the latest unreleased build?  This one may have a fix for this already:  [dxwrapper.zip](https://github.com/user-attachments/files/16920087/dxwrapper.zip)

**Comment by Omni4** [comment] 2024-09-07 23:49
Sadly not. The tables now give no output.

**Comment by elishacloud** [comment] 2024-09-08 02:21
It looks like it is hanging at or after:

```log
Installing memory management hooks
```

**Comment by elishacloud** [comment] 2024-09-08 02:33
1. Can you check if either of these files `dbghelp.dll` or `dbgeng.dll` exist in the game folder?  If so back them up and delete them.
2. Make sure you rename any ddraw or other similar patch from GOG.  These can conflict with my patch.
3. Try disabling any compatibility options for either of the exe files.

**Comment by Omni4** [comment] 2024-09-08 11:56
dbg dlls are not present. removed all loaders and dlls except for audiow32.dll because it's needed to run the game.
No compatibility options are applied. Still gives the same crashes at the same place.

**Comment by elishacloud** [comment] 2024-09-11 03:05
Ok, try this one.  I disabled all those hooks:  [dxwrapper.zip](https://github.com/user-attachments/files/16957345/dxwrapper.zip)

**Comment by Omni4** [comment] 2024-09-11 20:03
With this one the game works again, but still shows the cursor in the center of the screen.

**Comment by elishacloud** [comment] 2024-09-11 20:43
That build I just disable the features.  Would you mind helping me troubleshoot this so that the features actually work?

I made some changes and added some logging to this build:  [dxwrapper.zip](https://github.com/user-attachments/files/16970226/dxwrapper.zip)

This won't fix the mouse cursor issue, but I want to try and fix the other issue.  I will also make an option to hide the cursor later as well.

Let me know if this build works or not.  If it does not work please attach the debug build.  Also, if you have another game you can test this will that would be good.  Just to see if that is an issue with the game or your operating system.

**Comment by Omni4** [comment] 2024-09-11 21:48
This one crashes at the same place, at "Installing memory management hooks". 
[dxwrapper-barbarin.log](https://github.com/user-attachments/files/16970742/dxwrapper-barbarin.log)
I don't have much time atm. It's almost bedtime for me.

**Comment by Omni4** [comment] 2024-09-11 22:19
Tested it with Jazz Jackrabbit 2 and it gives the same crash.
It's loading the game, but there is nothing on screen. I have to stop the game via Task Manager.
[dxwrapper-jazz2.log](https://github.com/user-attachments/files/16970923/dxwrapper-jazz2.log)
I'm running it on Windows 11 build 27695.1000 rs_prerelease (Canary).
DxWrapper v1.1.6900.22 is working without this problem.

**Comment by elishacloud** [comment] 2024-09-11 22:25
Thanks for testing that.  I suspect that the issue is the pre-release build.  Should work with the release build.

As far as `DxWrapper v1.1.6900.22`, it does not have these features.

**Comment by Omni4** [comment] 2024-09-11 22:43
You're welcome! Here's a debug log in case you can use it: 
[dxwrapper-duke nukem.log](https://github.com/user-attachments/files/16971091/dxwrapper-duke.nukem.log)

**Comment by elishacloud** [comment] 2024-09-12 02:51
Thanks!  I plan to test the game later and fix any issues.  But this crash is unique to your computer so I am hoping to figure out where it has the issue.

Can you test with this one and give me the logs?  This will help me see where it crashes: [dxwrapper.zip](https://github.com/user-attachments/files/16972647/dxwrapper.zip)

**Comment by elishacloud** [comment] 2024-09-13 05:31
Do you know if there is a demo or some way for me to test the game?  The only one I could find was on Amazon for over $100.

**Comment by Omni4** [comment] 2024-09-13 06:16
Sorry,.. busy days here.
I see they removed it from GOG. Probably because of the Duke Nukem table… :/ I still have the GOG installer if you want it.

**Comment by Omni4** [comment] 2024-09-13 06:27
If you live in or near the US, you could try this option: [https://www.amazon.com/dp/B0006H0MGO/?tag=mobygames02-20&aod=1](url)

**Comment by elishacloud** [comment] 2024-09-13 06:34
That is for the a Pinball game called "Balls of Steel".  I thought you were playing Duke Nukem Forever: Balls of Steel Edition.  Correct me if I am wrong.

**Comment by elishacloud** [comment] 2024-09-13 06:35
Sure, happy to get the GOG version if you have a way to get it to me.

**Comment by Omni4** [comment] 2024-09-13 06:50
> That is for the a Pinball game called "Balls of Steel". I thought you were playing Duke Nukem Forever: Balls of Steel Edition. Correct me if I am wrong.

Ha,.. no. I'm playing the pinball game. A re-release is also available on Steam, but it has a custom loader and it's missing the Duke Nukem table.

**Comment by Omni4** [comment] 2024-09-13 07:36
> Thanks! I plan to test the game later and fix any issues. But this crash is unique to your computer so I am hoping to figure out where it has the issue.
> 
> Can you test with this one and give me the logs? This will help me see where it crashes: [dxwrapper.zip](https://github.com/user-attachments/files/16972647/dxwrapper.zip)

Here's the test log: 
[dxwrapper-barbarin.log](https://github.com/user-attachments/files/16990229/dxwrapper-barbarin.log)

**Comment by elishacloud** [comment] 2024-09-13 22:13
Here is the latest build.  This should fix the crash.  Also, I tested with [Balls of Steel](https://www.myabandonware.com/game/balls-of-steel-e1h) and Alt+Tab works fine for me.  Also, I am not seeing the cursor issue.

Here is the latest build:  [dxwrapper.zip](https://github.com/user-attachments/files/16999811/dxwrapper.zip)

**Comment by Omni4** [comment] 2024-09-14 14:15
Thanks! That build fixed the crash.
Alt+Tab did work for me also, I just have the cursor problem, but that is probably an early access problem.

Did you remove the DdrawCreateDeviceEarly function from this build? That changed the loading cursor into a regular cursor for me. That way I can swipe the cursor into a corner while loading a table. Now it's showing the loading cursor again.

**Comment by Omni4** [comment] 2024-09-14 14:40
I have an other request: Do you run Windows 11?
If so, can you share the DirectX files from your System32 and from your SysWOW64 folder? d3d*.* + ddraw*.* + dinput*.*?
I want to test if it has to do something with one of those files.

**Comment by elishacloud** [comment] 2024-09-23 03:28
I did not have Windows 11, but last week I installed in on VMware so I can test this.  It works fine for me.  Here is what I do:

1. I have the compatibility settings set to "Windows 98 / Windows ME"
2. I am using this build:  [dxwrapper.zip](https://github.com/user-attachments/files/17092398/dxwrapper.zip)

![image](https://github.com/user-attachments/assets/3937012e-0140-449e-a477-e1b3080a14cc)

If you think there is an issue with one of your files in Windows you can run `sfc /scannow` from an Administrative Command Prompt.  That should repair any damaged files.

**Comment by elishacloud** [comment] 2024-10-01 16:52
> Did you remove the DdrawCreateDeviceEarly function from this build?

I removed that because it caused issues with some games and I was trying to make it so that "extra" options are not needed to play games.  I want it so that you just set the singe `dd7to9` option and it works.

Anyways, I updated the build and now I always do early device creation.  I figured out the issue why some games don't work with early device creation and fixed it.

Try this build:  [dxwrapper.zip](https://github.com/user-attachments/files/17213240/dxwrapper.zip)

**Comment by Omni4** [comment] 2024-10-01 19:56
Hi,.. sorry for the late reply. Busy days here. I did run sfc /scannow several times before and it didn’t find any problems. I do think that I have a DirectX problem because I experience problems with some games like Avatar: Frontiers of Pandora. The game crashes frequently and when I use a DirectX to Vulkan wrapper, the game runs without crashes. That’s why I asked for the files. I think that not all DirectX files are checked with the System File Checher.
I’m not at home atm. But I’ll try to check the new build tomorrow.

**Comment by Omni4** [comment] 2024-10-02 09:30
Tested it today and it works, but I still have the cursor issue when I use the loader that's included with the GOG version. When I use the default loader (bos.exe) it does not have the cursor issue when a table is loaded, but the loader is stuck at the top left of the screen. Changing the compatibility settings to  "Windows 98 / Windows ME" makes no difference.

**Comment by elishacloud** [comment] 2024-10-02 22:47
I tried this game with Windows 7, 10 and 11.  All of them works for me.  Make sure you have all compatibility option disabled except Windows 95/98 (see screenshot below).

I cannot try it with GOG, I am using the original game.  Make sure you disable the GOG loader and any specific GOG files (ddraw.dll, dinput.dll, winmm.dll, etc.).  Backup the files before deleting them so you can put them back if needed.

Here is the latest build I tested with:  [dxwrapper.zip](https://github.com/user-attachments/files/17237061/dxwrapper.zip)

![image](https://github.com/user-attachments/assets/daa900ac-eb4f-458e-a7b5-b038fa0b3723)

**Comment by elishacloud** [comment] 2024-12-03 23:24
Can you try this build?  I tested on Windows 10 and 11 and I am not seeing any issues:  [dxwrapper.zip](https://github.com/user-attachments/files/18000472/dxwrapper.zip)

_BTW: you should no longer need to set any compatibility options._

**Comment by elishacloud** [comment] 2024-12-14 07:34
This is fixed with the latest release. You can reopen it if you are still having issues.

**Closed by elishacloud** 2024-12-14 07:34 UTC
