### ISSUE TITLE
Menu misalignment on G:OC fix

### ISSUE THREAD

**Issue by maxalthoff** [elishacloud/dxwrapper#4] opened 2017-08-05 15:16 UTC
The Gangsters: Organized Crime fix works like a charm at bringing menu text back (at least on the main menu), but the clickable areas of the buttons now appear to be misaligned, e.g. clicking somewhere on the left side of the Tutorial button exits out of the game. I followed the install procedure (extract dsound.dll and .ini into the game folder) and made sure to check the compatibility settings for the game .exe.

**Comment by sterling1930** [comment] 2018-02-07 19:40
Hello. I'm having same issue. Any advise hot to fix this?

**Comment by elishacloud** [comment] 2018-02-09 23:35
Hello salvatore,

What OS and video card are you using?

How do you have your Compatibility mode settings configured?  See here for how it should look:

![Compatibility](https://raw.githubusercontent.com/elishacloud/wiki-attachments/master/dxwrapper/Games/Gangsters%20Organized%20Crime/Compatibility.png)

**Comment by salvatore1930** [comment] 2018-02-11 14:20
Hello.
My OS is Win 10 Home with latest updates, video is GTX 1050 Ti (mobile). My compatibility setting is same as on the picture (all off). I'm using dsound.dll v1.0.990.18.

**Comment by elishacloud** [comment] 2018-02-13 01:53
Try this update and let me know if this solves the issue or not.

[dsound.zip](https://github.com/elishacloud/dxwrapper/files/1718318/dsound.zip)

**Comment by salvatore1930** [comment] 2018-02-14 05:41
Hello Elisha.

Here are my findings:
- Looks like that the zip you provided (just by comparing the included file sizes) is same as on this [GOC page](https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime). I will reference it further as the [GOC version](https://github.com/elishacloud/wiki-attachments/raw/master/dxwrapper/Games/Gangsters%20Organized%20Crime/gangsters-fix.zip).
- The GOC version behaves slightly better than the dll from the [latest release](https://github.com/elishacloud/dxwrapper/releases/download/v1.0.990.18/DxWrapper.zip) (by keeping the GOC version ini file). With the latest version texts in menu are black and unreadable comparing to the game's original text colors or colors when using the GOC version.

The issue is related to display custom scaling. My display is 4K I have the custom scale set to 250%.
- When I switch to 100% the mouse position issue is gone and the game works perfectly!!!
- When DPI behavior is set to "Scaling performed by Application" the mouse position problem is gone but the ingame mouse icon is huge. And I mean really HUGE :).
- When DPI behavior is set to "System" or "System (Enhanced)" the game won't start. There is this error displayed:

<img src="https://user-images.githubusercontent.com/36243266/36188539-f86c1fe8-114c-11e8-80e7-0f346e51b259.png" width="350">

I hope that this will help and you will be able to prepare some fix for displays with custom scaling.

Thanks.

**Comment by elishacloud** [comment] 2018-02-27 04:48
@salvatore1930, Try this update.  I changed the way I disable High DPI mode.  This does not fix the large mouse cursor but that only happens when setting up the game and I don't really want to mess with the mouse right now.  However this should allow you to play the game normally even if you have custom scaling set to 250%.

[dsound.zip](https://github.com/elishacloud/dxwrapper/files/1761278/dsound.zip)

**Comment by salvatore1930** [comment] 2018-02-28 20:15
Thanks for the fix!!!
Works as expected - no mouse positioning issues in the menu, except the cursor icon size.
PS1: Would you like me to create a new bug for the cursor issue?
PS2: You might update the zip file on the [GOC wiki page](https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime).
Thanks again.

**Comment by elishacloud** [comment] 2018-03-01 02:13
> PS1: Would you like me to create a new bug for the cursor issue?

Nope, I took note of it.  Frankly, I don't plan on fixing this any time soon since it does not really effect the game play.

> PS2: You might update the zip file on the GOC wiki page.

Yes, I was just waiting for confirmation from you that this fixed the issue.  The page has now been updated.  Thanks!

Closing this issue since the fix is confirmed.

**Closed by elishacloud** 2018-03-01 02:13 UTC
Labels: bug

**Comment by MFreeman555** [comment] 2020-04-10 16:11
Guys help me. I installed the game, added the above files from the dsound.zip archive, but the game still does not start. When the first picture of the game appears, the error "unable to open font file" appears and the game freezes. Please help me.

**Comment by mirh** [comment] 2020-05-06 11:31
[That](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/144#issuecomment-508988957) sounds like something is corrupted on your side. 
https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime
Besides anyway, these are the actual proper instruction. Not something from years ago.

**Comment by MrSankofa** [comment] 2020-09-28 13:21
Thank you very much for fixing this Elisha! I just wanted to confirm that that zip file and the instructions worked for me in 2020. I will be donating to you for your help!

**Comment by MrSankofa** [comment] 2020-09-28 13:22
Thank you very much for fixing this Elisha! I just wanted to confirm that that zip file and the instructions worked for me in 2020. I will be donating to you for your help!

**Comment by taylornotes** [comment] 2020-10-05 21:56
why wont GoG.com
 accept my payment i cant even buy it

**Comment by elishacloud** [comment] 2020-10-05 23:52
@taylornotes, You will need to talk to GoG.  I have no affiliations with GoG.
